name: Schedule Pro

on:
  push:
    branches: ["master"]

jobs: 
  CI_CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Muestra el contenido
        run: ls -la

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalación de dependencias
        run: npm install --no-audit --no-fund

      - name: Instalación de Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Compilar proyecto Angular
        run: ng build --configuration=production

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      # - name: Verificar token cargado
      #   run: ls -la ~/.firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Desplegar a Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"


    
