

name: Schedule Pro

on:
  push:
    branches: ["master"]

jobs: 
  despliegue:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Muestra el contenido
          run: ls -la

        - uses: actions/setup-node@v4
        - run: npm install --no-audit --no-found

        # - name: Instalacion de angular
        # - uses: actions/angular-github-actions
        - run: npm install -g @angular/cli@latest
        - run: ng version
        - run: ng build 
        
        - run: npm install -g firebase-tools
        - run: firebase login
        # - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} 


    
