

name: Schedule Pro

on:
  push:
    branches: ["master"]

jobs: 
  despliegue:
    runs-on: ubuntu-latest

    steps:
        - name: 'Hello world'
          run: echo "Hello world"
        - name: Muestra el contenido
          run: ls -la
    
